/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutTestImport } from './routes/_layout/test'
import { Route as LayoutAddClientImport } from './routes/_layout/add-client'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as LayoutUsersIndexImport } from './routes/_layout/users/index'
import { Route as LayoutMarginUpdatesIndexImport } from './routes/_layout/margin-updates/index'
import { Route as LayoutFundTransferIndexImport } from './routes/_layout/fund-transfer/index'
import { Route as LayoutDownloadsIndexImport } from './routes/_layout/downloads/index'
import { Route as LayoutUsersAddIndexImport } from './routes/_layout/users/add/index'
import { Route as LayoutResearchReportsWeeklyInsightsReportsIndexImport } from './routes/_layout/research-reports/weekly-insights-reports/index'
import { Route as LayoutResearchReportsSpecialReportsIndexImport } from './routes/_layout/research-reports/special-reports/index'
import { Route as LayoutResearchReportsMutualFundReportsIndexImport } from './routes/_layout/research-reports/mutual-fund-reports/index'
import { Route as LayoutResearchReportsMonthlyInsightsReportsIndexImport } from './routes/_layout/research-reports/monthly-insights-reports/index'
import { Route as LayoutResearchReportsFundamentalReportsIndexImport } from './routes/_layout/research-reports/fundamental-reports/index'
import { Route as LayoutResearchReportsDailyInsightsReportsIndexImport } from './routes/_layout/research-reports/daily-insights-reports/index'
import { Route as LayoutResearchReportsCommodityCurrencyReportsIndexImport } from './routes/_layout/research-reports/commodity-currency-reports/index'
import { Route as LayoutMarginUpdatesAddIndexImport } from './routes/_layout/margin-updates/add/index'
import { Route as LayoutFundTransferAddClientIndexImport } from './routes/_layout/fund-transfer/add-client/index'
import { Route as LayoutDownloadsAddIndexImport } from './routes/_layout/downloads/add/index'
import { Route as LayoutAcclPoliciesReportsIndexImport } from './routes/_layout/accl/policies-reports/index'
import { Route as LayoutAcclInvestorRelationsReportsIndexImport } from './routes/_layout/accl/investor-relations-reports/index'
import { Route as LayoutAcclFamiliarizationProgrammeReportsIndexImport } from './routes/_layout/accl/familiarization-programme-reports/index'
import { Route as LayoutAcclAnnualReportsIndexImport } from './routes/_layout/accl/annual-reports/index'
import { Route as LayoutMarginUpdatesReportIdUpdateImport } from './routes/_layout/margin-updates/$reportId/update'
import { Route as LayoutDownloadsReportIdUpdateImport } from './routes/_layout/downloads/$reportId/update'
import { Route as LayoutResearchReportsWeeklyInsightsReportsAddIndexImport } from './routes/_layout/research-reports/weekly-insights-reports/add/index'
import { Route as LayoutResearchReportsSpecialReportsAddIndexImport } from './routes/_layout/research-reports/special-reports/add/index'
import { Route as LayoutResearchReportsMutualFundReportsAddIndexImport } from './routes/_layout/research-reports/mutual-fund-reports/add/index'
import { Route as LayoutResearchReportsMonthlyInsightsReportsAddIndexImport } from './routes/_layout/research-reports/monthly-insights-reports/add/index'
import { Route as LayoutResearchReportsFundamentalReportsAddIndexImport } from './routes/_layout/research-reports/fundamental-reports/add/index'
import { Route as LayoutResearchReportsDailyInsightsReportsAddIndexImport } from './routes/_layout/research-reports/daily-insights-reports/add/index'
import { Route as LayoutResearchReportsCommodityCurrencyReportsAddIndexImport } from './routes/_layout/research-reports/commodity-currency-reports/add/index'
import { Route as LayoutAcclPoliciesReportsAddIndexImport } from './routes/_layout/accl/policies-reports/add/index'
import { Route as LayoutAcclInvestorRelationsReportsAddIndexImport } from './routes/_layout/accl/investor-relations-reports/add/index'
import { Route as LayoutAcclFamiliarizationProgrammeReportsAddIndexImport } from './routes/_layout/accl/familiarization-programme-reports/add/index'
import { Route as LayoutAcclAnnualReportsAddIndexImport } from './routes/_layout/accl/annual-reports/add/index'
import { Route as LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateImport } from './routes/_layout/research-reports/weekly-insights-reports/$reportId/update'
import { Route as LayoutResearchReportsSpecialReportsReportIdUpdateImport } from './routes/_layout/research-reports/special-reports/$reportId/update'
import { Route as LayoutResearchReportsMutualFundReportsReportIdUpdateImport } from './routes/_layout/research-reports/mutual-fund-reports/$reportId/update'
import { Route as LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateImport } from './routes/_layout/research-reports/monthly-insights-reports/$reportId/update'
import { Route as LayoutResearchReportsFundamentalReportsReportIdUpdateImport } from './routes/_layout/research-reports/fundamental-reports/$reportId/update'
import { Route as LayoutResearchReportsDailyInsightsReportsReportIdUpdateImport } from './routes/_layout/research-reports/daily-insights-reports/$reportId/update'
import { Route as LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateImport } from './routes/_layout/research-reports/commodity-currency-reports/$reportId/update'
import { Route as LayoutAcclPoliciesReportsReportIdUpdateImport } from './routes/_layout/accl/policies-reports/$reportId/update'
import { Route as LayoutAcclInvestorRelationsReportsReportIdUpdateImport } from './routes/_layout/accl/investor-relations-reports/$reportId/update'
import { Route as LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateImport } from './routes/_layout/accl/familiarization-programme-reports/$reportId/update'
import { Route as LayoutAcclAnnualReportsReportIdUpdateImport } from './routes/_layout/accl/annual-reports/$reportId/update'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTestRoute = LayoutTestImport.update({
  path: '/test',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAddClientRoute = LayoutAddClientImport.update({
  path: '/add-client',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUsersIndexRoute = LayoutUsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutMarginUpdatesIndexRoute = LayoutMarginUpdatesIndexImport.update({
  path: '/margin-updates/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFundTransferIndexRoute = LayoutFundTransferIndexImport.update({
  path: '/fund-transfer/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDownloadsIndexRoute = LayoutDownloadsIndexImport.update({
  path: '/downloads/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUsersAddIndexRoute = LayoutUsersAddIndexImport.update({
  path: '/users/add/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutResearchReportsWeeklyInsightsReportsIndexRoute =
  LayoutResearchReportsWeeklyInsightsReportsIndexImport.update({
    path: '/research-reports/weekly-insights-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsSpecialReportsIndexRoute =
  LayoutResearchReportsSpecialReportsIndexImport.update({
    path: '/research-reports/special-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsMutualFundReportsIndexRoute =
  LayoutResearchReportsMutualFundReportsIndexImport.update({
    path: '/research-reports/mutual-fund-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsMonthlyInsightsReportsIndexRoute =
  LayoutResearchReportsMonthlyInsightsReportsIndexImport.update({
    path: '/research-reports/monthly-insights-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsFundamentalReportsIndexRoute =
  LayoutResearchReportsFundamentalReportsIndexImport.update({
    path: '/research-reports/fundamental-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsDailyInsightsReportsIndexRoute =
  LayoutResearchReportsDailyInsightsReportsIndexImport.update({
    path: '/research-reports/daily-insights-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsCommodityCurrencyReportsIndexRoute =
  LayoutResearchReportsCommodityCurrencyReportsIndexImport.update({
    path: '/research-reports/commodity-currency-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutMarginUpdatesAddIndexRoute =
  LayoutMarginUpdatesAddIndexImport.update({
    path: '/margin-updates/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutFundTransferAddClientIndexRoute =
  LayoutFundTransferAddClientIndexImport.update({
    path: '/fund-transfer/add-client/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDownloadsAddIndexRoute = LayoutDownloadsAddIndexImport.update({
  path: '/downloads/add/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAcclPoliciesReportsIndexRoute =
  LayoutAcclPoliciesReportsIndexImport.update({
    path: '/accl/policies-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclInvestorRelationsReportsIndexRoute =
  LayoutAcclInvestorRelationsReportsIndexImport.update({
    path: '/accl/investor-relations-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclFamiliarizationProgrammeReportsIndexRoute =
  LayoutAcclFamiliarizationProgrammeReportsIndexImport.update({
    path: '/accl/familiarization-programme-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclAnnualReportsIndexRoute =
  LayoutAcclAnnualReportsIndexImport.update({
    path: '/accl/annual-reports/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutMarginUpdatesReportIdUpdateRoute =
  LayoutMarginUpdatesReportIdUpdateImport.update({
    path: '/margin-updates/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDownloadsReportIdUpdateRoute =
  LayoutDownloadsReportIdUpdateImport.update({
    path: '/downloads/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsWeeklyInsightsReportsAddIndexRoute =
  LayoutResearchReportsWeeklyInsightsReportsAddIndexImport.update({
    path: '/research-reports/weekly-insights-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsSpecialReportsAddIndexRoute =
  LayoutResearchReportsSpecialReportsAddIndexImport.update({
    path: '/research-reports/special-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsMutualFundReportsAddIndexRoute =
  LayoutResearchReportsMutualFundReportsAddIndexImport.update({
    path: '/research-reports/mutual-fund-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsMonthlyInsightsReportsAddIndexRoute =
  LayoutResearchReportsMonthlyInsightsReportsAddIndexImport.update({
    path: '/research-reports/monthly-insights-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsFundamentalReportsAddIndexRoute =
  LayoutResearchReportsFundamentalReportsAddIndexImport.update({
    path: '/research-reports/fundamental-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsDailyInsightsReportsAddIndexRoute =
  LayoutResearchReportsDailyInsightsReportsAddIndexImport.update({
    path: '/research-reports/daily-insights-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsCommodityCurrencyReportsAddIndexRoute =
  LayoutResearchReportsCommodityCurrencyReportsAddIndexImport.update({
    path: '/research-reports/commodity-currency-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclPoliciesReportsAddIndexRoute =
  LayoutAcclPoliciesReportsAddIndexImport.update({
    path: '/accl/policies-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclInvestorRelationsReportsAddIndexRoute =
  LayoutAcclInvestorRelationsReportsAddIndexImport.update({
    path: '/accl/investor-relations-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclFamiliarizationProgrammeReportsAddIndexRoute =
  LayoutAcclFamiliarizationProgrammeReportsAddIndexImport.update({
    path: '/accl/familiarization-programme-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclAnnualReportsAddIndexRoute =
  LayoutAcclAnnualReportsAddIndexImport.update({
    path: '/accl/annual-reports/add/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateRoute =
  LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateImport.update({
    path: '/research-reports/weekly-insights-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsSpecialReportsReportIdUpdateRoute =
  LayoutResearchReportsSpecialReportsReportIdUpdateImport.update({
    path: '/research-reports/special-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsMutualFundReportsReportIdUpdateRoute =
  LayoutResearchReportsMutualFundReportsReportIdUpdateImport.update({
    path: '/research-reports/mutual-fund-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateRoute =
  LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateImport.update({
    path: '/research-reports/monthly-insights-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsFundamentalReportsReportIdUpdateRoute =
  LayoutResearchReportsFundamentalReportsReportIdUpdateImport.update({
    path: '/research-reports/fundamental-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsDailyInsightsReportsReportIdUpdateRoute =
  LayoutResearchReportsDailyInsightsReportsReportIdUpdateImport.update({
    path: '/research-reports/daily-insights-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateRoute =
  LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateImport.update({
    path: '/research-reports/commodity-currency-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclPoliciesReportsReportIdUpdateRoute =
  LayoutAcclPoliciesReportsReportIdUpdateImport.update({
    path: '/accl/policies-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclInvestorRelationsReportsReportIdUpdateRoute =
  LayoutAcclInvestorRelationsReportsReportIdUpdateImport.update({
    path: '/accl/investor-relations-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateRoute =
  LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateImport.update({
    path: '/accl/familiarization-programme-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAcclAnnualReportsReportIdUpdateRoute =
  LayoutAcclAnnualReportsReportIdUpdateImport.update({
    path: '/accl/annual-reports/$reportId/update',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/add-client': {
      id: '/_layout/add-client'
      path: '/add-client'
      fullPath: '/add-client'
      preLoaderRoute: typeof LayoutAddClientImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/test': {
      id: '/_layout/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof LayoutTestImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/downloads/': {
      id: '/_layout/downloads/'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof LayoutDownloadsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/fund-transfer/': {
      id: '/_layout/fund-transfer/'
      path: '/fund-transfer'
      fullPath: '/fund-transfer'
      preLoaderRoute: typeof LayoutFundTransferIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/margin-updates/': {
      id: '/_layout/margin-updates/'
      path: '/margin-updates'
      fullPath: '/margin-updates'
      preLoaderRoute: typeof LayoutMarginUpdatesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/downloads/$reportId/update': {
      id: '/_layout/downloads/$reportId/update'
      path: '/downloads/$reportId/update'
      fullPath: '/downloads/$reportId/update'
      preLoaderRoute: typeof LayoutDownloadsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/margin-updates/$reportId/update': {
      id: '/_layout/margin-updates/$reportId/update'
      path: '/margin-updates/$reportId/update'
      fullPath: '/margin-updates/$reportId/update'
      preLoaderRoute: typeof LayoutMarginUpdatesReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/annual-reports/': {
      id: '/_layout/accl/annual-reports/'
      path: '/accl/annual-reports'
      fullPath: '/accl/annual-reports'
      preLoaderRoute: typeof LayoutAcclAnnualReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/familiarization-programme-reports/': {
      id: '/_layout/accl/familiarization-programme-reports/'
      path: '/accl/familiarization-programme-reports'
      fullPath: '/accl/familiarization-programme-reports'
      preLoaderRoute: typeof LayoutAcclFamiliarizationProgrammeReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/investor-relations-reports/': {
      id: '/_layout/accl/investor-relations-reports/'
      path: '/accl/investor-relations-reports'
      fullPath: '/accl/investor-relations-reports'
      preLoaderRoute: typeof LayoutAcclInvestorRelationsReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/policies-reports/': {
      id: '/_layout/accl/policies-reports/'
      path: '/accl/policies-reports'
      fullPath: '/accl/policies-reports'
      preLoaderRoute: typeof LayoutAcclPoliciesReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/downloads/add/': {
      id: '/_layout/downloads/add/'
      path: '/downloads/add'
      fullPath: '/downloads/add'
      preLoaderRoute: typeof LayoutDownloadsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/fund-transfer/add-client/': {
      id: '/_layout/fund-transfer/add-client/'
      path: '/fund-transfer/add-client'
      fullPath: '/fund-transfer/add-client'
      preLoaderRoute: typeof LayoutFundTransferAddClientIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/margin-updates/add/': {
      id: '/_layout/margin-updates/add/'
      path: '/margin-updates/add'
      fullPath: '/margin-updates/add'
      preLoaderRoute: typeof LayoutMarginUpdatesAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/commodity-currency-reports/': {
      id: '/_layout/research-reports/commodity-currency-reports/'
      path: '/research-reports/commodity-currency-reports'
      fullPath: '/research-reports/commodity-currency-reports'
      preLoaderRoute: typeof LayoutResearchReportsCommodityCurrencyReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/daily-insights-reports/': {
      id: '/_layout/research-reports/daily-insights-reports/'
      path: '/research-reports/daily-insights-reports'
      fullPath: '/research-reports/daily-insights-reports'
      preLoaderRoute: typeof LayoutResearchReportsDailyInsightsReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/fundamental-reports/': {
      id: '/_layout/research-reports/fundamental-reports/'
      path: '/research-reports/fundamental-reports'
      fullPath: '/research-reports/fundamental-reports'
      preLoaderRoute: typeof LayoutResearchReportsFundamentalReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/monthly-insights-reports/': {
      id: '/_layout/research-reports/monthly-insights-reports/'
      path: '/research-reports/monthly-insights-reports'
      fullPath: '/research-reports/monthly-insights-reports'
      preLoaderRoute: typeof LayoutResearchReportsMonthlyInsightsReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/mutual-fund-reports/': {
      id: '/_layout/research-reports/mutual-fund-reports/'
      path: '/research-reports/mutual-fund-reports'
      fullPath: '/research-reports/mutual-fund-reports'
      preLoaderRoute: typeof LayoutResearchReportsMutualFundReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/special-reports/': {
      id: '/_layout/research-reports/special-reports/'
      path: '/research-reports/special-reports'
      fullPath: '/research-reports/special-reports'
      preLoaderRoute: typeof LayoutResearchReportsSpecialReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/weekly-insights-reports/': {
      id: '/_layout/research-reports/weekly-insights-reports/'
      path: '/research-reports/weekly-insights-reports'
      fullPath: '/research-reports/weekly-insights-reports'
      preLoaderRoute: typeof LayoutResearchReportsWeeklyInsightsReportsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/users/add/': {
      id: '/_layout/users/add/'
      path: '/users/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof LayoutUsersAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/annual-reports/$reportId/update': {
      id: '/_layout/accl/annual-reports/$reportId/update'
      path: '/accl/annual-reports/$reportId/update'
      fullPath: '/accl/annual-reports/$reportId/update'
      preLoaderRoute: typeof LayoutAcclAnnualReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/familiarization-programme-reports/$reportId/update': {
      id: '/_layout/accl/familiarization-programme-reports/$reportId/update'
      path: '/accl/familiarization-programme-reports/$reportId/update'
      fullPath: '/accl/familiarization-programme-reports/$reportId/update'
      preLoaderRoute: typeof LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/investor-relations-reports/$reportId/update': {
      id: '/_layout/accl/investor-relations-reports/$reportId/update'
      path: '/accl/investor-relations-reports/$reportId/update'
      fullPath: '/accl/investor-relations-reports/$reportId/update'
      preLoaderRoute: typeof LayoutAcclInvestorRelationsReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/policies-reports/$reportId/update': {
      id: '/_layout/accl/policies-reports/$reportId/update'
      path: '/accl/policies-reports/$reportId/update'
      fullPath: '/accl/policies-reports/$reportId/update'
      preLoaderRoute: typeof LayoutAcclPoliciesReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/commodity-currency-reports/$reportId/update': {
      id: '/_layout/research-reports/commodity-currency-reports/$reportId/update'
      path: '/research-reports/commodity-currency-reports/$reportId/update'
      fullPath: '/research-reports/commodity-currency-reports/$reportId/update'
      preLoaderRoute: typeof LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/daily-insights-reports/$reportId/update': {
      id: '/_layout/research-reports/daily-insights-reports/$reportId/update'
      path: '/research-reports/daily-insights-reports/$reportId/update'
      fullPath: '/research-reports/daily-insights-reports/$reportId/update'
      preLoaderRoute: typeof LayoutResearchReportsDailyInsightsReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/fundamental-reports/$reportId/update': {
      id: '/_layout/research-reports/fundamental-reports/$reportId/update'
      path: '/research-reports/fundamental-reports/$reportId/update'
      fullPath: '/research-reports/fundamental-reports/$reportId/update'
      preLoaderRoute: typeof LayoutResearchReportsFundamentalReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/monthly-insights-reports/$reportId/update': {
      id: '/_layout/research-reports/monthly-insights-reports/$reportId/update'
      path: '/research-reports/monthly-insights-reports/$reportId/update'
      fullPath: '/research-reports/monthly-insights-reports/$reportId/update'
      preLoaderRoute: typeof LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/mutual-fund-reports/$reportId/update': {
      id: '/_layout/research-reports/mutual-fund-reports/$reportId/update'
      path: '/research-reports/mutual-fund-reports/$reportId/update'
      fullPath: '/research-reports/mutual-fund-reports/$reportId/update'
      preLoaderRoute: typeof LayoutResearchReportsMutualFundReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/special-reports/$reportId/update': {
      id: '/_layout/research-reports/special-reports/$reportId/update'
      path: '/research-reports/special-reports/$reportId/update'
      fullPath: '/research-reports/special-reports/$reportId/update'
      preLoaderRoute: typeof LayoutResearchReportsSpecialReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/weekly-insights-reports/$reportId/update': {
      id: '/_layout/research-reports/weekly-insights-reports/$reportId/update'
      path: '/research-reports/weekly-insights-reports/$reportId/update'
      fullPath: '/research-reports/weekly-insights-reports/$reportId/update'
      preLoaderRoute: typeof LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/annual-reports/add/': {
      id: '/_layout/accl/annual-reports/add/'
      path: '/accl/annual-reports/add'
      fullPath: '/accl/annual-reports/add'
      preLoaderRoute: typeof LayoutAcclAnnualReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/familiarization-programme-reports/add/': {
      id: '/_layout/accl/familiarization-programme-reports/add/'
      path: '/accl/familiarization-programme-reports/add'
      fullPath: '/accl/familiarization-programme-reports/add'
      preLoaderRoute: typeof LayoutAcclFamiliarizationProgrammeReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/investor-relations-reports/add/': {
      id: '/_layout/accl/investor-relations-reports/add/'
      path: '/accl/investor-relations-reports/add'
      fullPath: '/accl/investor-relations-reports/add'
      preLoaderRoute: typeof LayoutAcclInvestorRelationsReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/accl/policies-reports/add/': {
      id: '/_layout/accl/policies-reports/add/'
      path: '/accl/policies-reports/add'
      fullPath: '/accl/policies-reports/add'
      preLoaderRoute: typeof LayoutAcclPoliciesReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/commodity-currency-reports/add/': {
      id: '/_layout/research-reports/commodity-currency-reports/add/'
      path: '/research-reports/commodity-currency-reports/add'
      fullPath: '/research-reports/commodity-currency-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsCommodityCurrencyReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/daily-insights-reports/add/': {
      id: '/_layout/research-reports/daily-insights-reports/add/'
      path: '/research-reports/daily-insights-reports/add'
      fullPath: '/research-reports/daily-insights-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsDailyInsightsReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/fundamental-reports/add/': {
      id: '/_layout/research-reports/fundamental-reports/add/'
      path: '/research-reports/fundamental-reports/add'
      fullPath: '/research-reports/fundamental-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsFundamentalReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/monthly-insights-reports/add/': {
      id: '/_layout/research-reports/monthly-insights-reports/add/'
      path: '/research-reports/monthly-insights-reports/add'
      fullPath: '/research-reports/monthly-insights-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsMonthlyInsightsReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/mutual-fund-reports/add/': {
      id: '/_layout/research-reports/mutual-fund-reports/add/'
      path: '/research-reports/mutual-fund-reports/add'
      fullPath: '/research-reports/mutual-fund-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsMutualFundReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/special-reports/add/': {
      id: '/_layout/research-reports/special-reports/add/'
      path: '/research-reports/special-reports/add'
      fullPath: '/research-reports/special-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsSpecialReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/research-reports/weekly-insights-reports/add/': {
      id: '/_layout/research-reports/weekly-insights-reports/add/'
      path: '/research-reports/weekly-insights-reports/add'
      fullPath: '/research-reports/weekly-insights-reports/add'
      preLoaderRoute: typeof LayoutResearchReportsWeeklyInsightsReportsAddIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutAddClientRoute: typeof LayoutAddClientRoute
  LayoutTestRoute: typeof LayoutTestRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDownloadsIndexRoute: typeof LayoutDownloadsIndexRoute
  LayoutFundTransferIndexRoute: typeof LayoutFundTransferIndexRoute
  LayoutMarginUpdatesIndexRoute: typeof LayoutMarginUpdatesIndexRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
  LayoutDownloadsReportIdUpdateRoute: typeof LayoutDownloadsReportIdUpdateRoute
  LayoutMarginUpdatesReportIdUpdateRoute: typeof LayoutMarginUpdatesReportIdUpdateRoute
  LayoutAcclAnnualReportsIndexRoute: typeof LayoutAcclAnnualReportsIndexRoute
  LayoutAcclFamiliarizationProgrammeReportsIndexRoute: typeof LayoutAcclFamiliarizationProgrammeReportsIndexRoute
  LayoutAcclInvestorRelationsReportsIndexRoute: typeof LayoutAcclInvestorRelationsReportsIndexRoute
  LayoutAcclPoliciesReportsIndexRoute: typeof LayoutAcclPoliciesReportsIndexRoute
  LayoutDownloadsAddIndexRoute: typeof LayoutDownloadsAddIndexRoute
  LayoutFundTransferAddClientIndexRoute: typeof LayoutFundTransferAddClientIndexRoute
  LayoutMarginUpdatesAddIndexRoute: typeof LayoutMarginUpdatesAddIndexRoute
  LayoutResearchReportsCommodityCurrencyReportsIndexRoute: typeof LayoutResearchReportsCommodityCurrencyReportsIndexRoute
  LayoutResearchReportsDailyInsightsReportsIndexRoute: typeof LayoutResearchReportsDailyInsightsReportsIndexRoute
  LayoutResearchReportsFundamentalReportsIndexRoute: typeof LayoutResearchReportsFundamentalReportsIndexRoute
  LayoutResearchReportsMonthlyInsightsReportsIndexRoute: typeof LayoutResearchReportsMonthlyInsightsReportsIndexRoute
  LayoutResearchReportsMutualFundReportsIndexRoute: typeof LayoutResearchReportsMutualFundReportsIndexRoute
  LayoutResearchReportsSpecialReportsIndexRoute: typeof LayoutResearchReportsSpecialReportsIndexRoute
  LayoutResearchReportsWeeklyInsightsReportsIndexRoute: typeof LayoutResearchReportsWeeklyInsightsReportsIndexRoute
  LayoutUsersAddIndexRoute: typeof LayoutUsersAddIndexRoute
  LayoutAcclAnnualReportsReportIdUpdateRoute: typeof LayoutAcclAnnualReportsReportIdUpdateRoute
  LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateRoute: typeof LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateRoute
  LayoutAcclInvestorRelationsReportsReportIdUpdateRoute: typeof LayoutAcclInvestorRelationsReportsReportIdUpdateRoute
  LayoutAcclPoliciesReportsReportIdUpdateRoute: typeof LayoutAcclPoliciesReportsReportIdUpdateRoute
  LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateRoute: typeof LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateRoute
  LayoutResearchReportsDailyInsightsReportsReportIdUpdateRoute: typeof LayoutResearchReportsDailyInsightsReportsReportIdUpdateRoute
  LayoutResearchReportsFundamentalReportsReportIdUpdateRoute: typeof LayoutResearchReportsFundamentalReportsReportIdUpdateRoute
  LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateRoute: typeof LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateRoute
  LayoutResearchReportsMutualFundReportsReportIdUpdateRoute: typeof LayoutResearchReportsMutualFundReportsReportIdUpdateRoute
  LayoutResearchReportsSpecialReportsReportIdUpdateRoute: typeof LayoutResearchReportsSpecialReportsReportIdUpdateRoute
  LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateRoute: typeof LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateRoute
  LayoutAcclAnnualReportsAddIndexRoute: typeof LayoutAcclAnnualReportsAddIndexRoute
  LayoutAcclFamiliarizationProgrammeReportsAddIndexRoute: typeof LayoutAcclFamiliarizationProgrammeReportsAddIndexRoute
  LayoutAcclInvestorRelationsReportsAddIndexRoute: typeof LayoutAcclInvestorRelationsReportsAddIndexRoute
  LayoutAcclPoliciesReportsAddIndexRoute: typeof LayoutAcclPoliciesReportsAddIndexRoute
  LayoutResearchReportsCommodityCurrencyReportsAddIndexRoute: typeof LayoutResearchReportsCommodityCurrencyReportsAddIndexRoute
  LayoutResearchReportsDailyInsightsReportsAddIndexRoute: typeof LayoutResearchReportsDailyInsightsReportsAddIndexRoute
  LayoutResearchReportsFundamentalReportsAddIndexRoute: typeof LayoutResearchReportsFundamentalReportsAddIndexRoute
  LayoutResearchReportsMonthlyInsightsReportsAddIndexRoute: typeof LayoutResearchReportsMonthlyInsightsReportsAddIndexRoute
  LayoutResearchReportsMutualFundReportsAddIndexRoute: typeof LayoutResearchReportsMutualFundReportsAddIndexRoute
  LayoutResearchReportsSpecialReportsAddIndexRoute: typeof LayoutResearchReportsSpecialReportsAddIndexRoute
  LayoutResearchReportsWeeklyInsightsReportsAddIndexRoute: typeof LayoutResearchReportsWeeklyInsightsReportsAddIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutAddClientRoute: LayoutAddClientRoute,
  LayoutTestRoute: LayoutTestRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDownloadsIndexRoute: LayoutDownloadsIndexRoute,
  LayoutFundTransferIndexRoute: LayoutFundTransferIndexRoute,
  LayoutMarginUpdatesIndexRoute: LayoutMarginUpdatesIndexRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
  LayoutDownloadsReportIdUpdateRoute: LayoutDownloadsReportIdUpdateRoute,
  LayoutMarginUpdatesReportIdUpdateRoute:
    LayoutMarginUpdatesReportIdUpdateRoute,
  LayoutAcclAnnualReportsIndexRoute: LayoutAcclAnnualReportsIndexRoute,
  LayoutAcclFamiliarizationProgrammeReportsIndexRoute:
    LayoutAcclFamiliarizationProgrammeReportsIndexRoute,
  LayoutAcclInvestorRelationsReportsIndexRoute:
    LayoutAcclInvestorRelationsReportsIndexRoute,
  LayoutAcclPoliciesReportsIndexRoute: LayoutAcclPoliciesReportsIndexRoute,
  LayoutDownloadsAddIndexRoute: LayoutDownloadsAddIndexRoute,
  LayoutFundTransferAddClientIndexRoute: LayoutFundTransferAddClientIndexRoute,
  LayoutMarginUpdatesAddIndexRoute: LayoutMarginUpdatesAddIndexRoute,
  LayoutResearchReportsCommodityCurrencyReportsIndexRoute:
    LayoutResearchReportsCommodityCurrencyReportsIndexRoute,
  LayoutResearchReportsDailyInsightsReportsIndexRoute:
    LayoutResearchReportsDailyInsightsReportsIndexRoute,
  LayoutResearchReportsFundamentalReportsIndexRoute:
    LayoutResearchReportsFundamentalReportsIndexRoute,
  LayoutResearchReportsMonthlyInsightsReportsIndexRoute:
    LayoutResearchReportsMonthlyInsightsReportsIndexRoute,
  LayoutResearchReportsMutualFundReportsIndexRoute:
    LayoutResearchReportsMutualFundReportsIndexRoute,
  LayoutResearchReportsSpecialReportsIndexRoute:
    LayoutResearchReportsSpecialReportsIndexRoute,
  LayoutResearchReportsWeeklyInsightsReportsIndexRoute:
    LayoutResearchReportsWeeklyInsightsReportsIndexRoute,
  LayoutUsersAddIndexRoute: LayoutUsersAddIndexRoute,
  LayoutAcclAnnualReportsReportIdUpdateRoute:
    LayoutAcclAnnualReportsReportIdUpdateRoute,
  LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateRoute:
    LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateRoute,
  LayoutAcclInvestorRelationsReportsReportIdUpdateRoute:
    LayoutAcclInvestorRelationsReportsReportIdUpdateRoute,
  LayoutAcclPoliciesReportsReportIdUpdateRoute:
    LayoutAcclPoliciesReportsReportIdUpdateRoute,
  LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateRoute:
    LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateRoute,
  LayoutResearchReportsDailyInsightsReportsReportIdUpdateRoute:
    LayoutResearchReportsDailyInsightsReportsReportIdUpdateRoute,
  LayoutResearchReportsFundamentalReportsReportIdUpdateRoute:
    LayoutResearchReportsFundamentalReportsReportIdUpdateRoute,
  LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateRoute:
    LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateRoute,
  LayoutResearchReportsMutualFundReportsReportIdUpdateRoute:
    LayoutResearchReportsMutualFundReportsReportIdUpdateRoute,
  LayoutResearchReportsSpecialReportsReportIdUpdateRoute:
    LayoutResearchReportsSpecialReportsReportIdUpdateRoute,
  LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateRoute:
    LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateRoute,
  LayoutAcclAnnualReportsAddIndexRoute: LayoutAcclAnnualReportsAddIndexRoute,
  LayoutAcclFamiliarizationProgrammeReportsAddIndexRoute:
    LayoutAcclFamiliarizationProgrammeReportsAddIndexRoute,
  LayoutAcclInvestorRelationsReportsAddIndexRoute:
    LayoutAcclInvestorRelationsReportsAddIndexRoute,
  LayoutAcclPoliciesReportsAddIndexRoute:
    LayoutAcclPoliciesReportsAddIndexRoute,
  LayoutResearchReportsCommodityCurrencyReportsAddIndexRoute:
    LayoutResearchReportsCommodityCurrencyReportsAddIndexRoute,
  LayoutResearchReportsDailyInsightsReportsAddIndexRoute:
    LayoutResearchReportsDailyInsightsReportsAddIndexRoute,
  LayoutResearchReportsFundamentalReportsAddIndexRoute:
    LayoutResearchReportsFundamentalReportsAddIndexRoute,
  LayoutResearchReportsMonthlyInsightsReportsAddIndexRoute:
    LayoutResearchReportsMonthlyInsightsReportsAddIndexRoute,
  LayoutResearchReportsMutualFundReportsAddIndexRoute:
    LayoutResearchReportsMutualFundReportsAddIndexRoute,
  LayoutResearchReportsSpecialReportsAddIndexRoute:
    LayoutResearchReportsSpecialReportsAddIndexRoute,
  LayoutResearchReportsWeeklyInsightsReportsAddIndexRoute:
    LayoutResearchReportsWeeklyInsightsReportsAddIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '': typeof LayoutRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/add-client': typeof LayoutAddClientRoute
  '/test': typeof LayoutTestRoute
  '/downloads': typeof LayoutDownloadsIndexRoute
  '/fund-transfer': typeof LayoutFundTransferIndexRoute
  '/margin-updates': typeof LayoutMarginUpdatesIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/downloads/$reportId/update': typeof LayoutDownloadsReportIdUpdateRoute
  '/margin-updates/$reportId/update': typeof LayoutMarginUpdatesReportIdUpdateRoute
  '/accl/annual-reports': typeof LayoutAcclAnnualReportsIndexRoute
  '/accl/familiarization-programme-reports': typeof LayoutAcclFamiliarizationProgrammeReportsIndexRoute
  '/accl/investor-relations-reports': typeof LayoutAcclInvestorRelationsReportsIndexRoute
  '/accl/policies-reports': typeof LayoutAcclPoliciesReportsIndexRoute
  '/downloads/add': typeof LayoutDownloadsAddIndexRoute
  '/fund-transfer/add-client': typeof LayoutFundTransferAddClientIndexRoute
  '/margin-updates/add': typeof LayoutMarginUpdatesAddIndexRoute
  '/research-reports/commodity-currency-reports': typeof LayoutResearchReportsCommodityCurrencyReportsIndexRoute
  '/research-reports/daily-insights-reports': typeof LayoutResearchReportsDailyInsightsReportsIndexRoute
  '/research-reports/fundamental-reports': typeof LayoutResearchReportsFundamentalReportsIndexRoute
  '/research-reports/monthly-insights-reports': typeof LayoutResearchReportsMonthlyInsightsReportsIndexRoute
  '/research-reports/mutual-fund-reports': typeof LayoutResearchReportsMutualFundReportsIndexRoute
  '/research-reports/special-reports': typeof LayoutResearchReportsSpecialReportsIndexRoute
  '/research-reports/weekly-insights-reports': typeof LayoutResearchReportsWeeklyInsightsReportsIndexRoute
  '/users/add': typeof LayoutUsersAddIndexRoute
  '/accl/annual-reports/$reportId/update': typeof LayoutAcclAnnualReportsReportIdUpdateRoute
  '/accl/familiarization-programme-reports/$reportId/update': typeof LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateRoute
  '/accl/investor-relations-reports/$reportId/update': typeof LayoutAcclInvestorRelationsReportsReportIdUpdateRoute
  '/accl/policies-reports/$reportId/update': typeof LayoutAcclPoliciesReportsReportIdUpdateRoute
  '/research-reports/commodity-currency-reports/$reportId/update': typeof LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateRoute
  '/research-reports/daily-insights-reports/$reportId/update': typeof LayoutResearchReportsDailyInsightsReportsReportIdUpdateRoute
  '/research-reports/fundamental-reports/$reportId/update': typeof LayoutResearchReportsFundamentalReportsReportIdUpdateRoute
  '/research-reports/monthly-insights-reports/$reportId/update': typeof LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateRoute
  '/research-reports/mutual-fund-reports/$reportId/update': typeof LayoutResearchReportsMutualFundReportsReportIdUpdateRoute
  '/research-reports/special-reports/$reportId/update': typeof LayoutResearchReportsSpecialReportsReportIdUpdateRoute
  '/research-reports/weekly-insights-reports/$reportId/update': typeof LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateRoute
  '/accl/annual-reports/add': typeof LayoutAcclAnnualReportsAddIndexRoute
  '/accl/familiarization-programme-reports/add': typeof LayoutAcclFamiliarizationProgrammeReportsAddIndexRoute
  '/accl/investor-relations-reports/add': typeof LayoutAcclInvestorRelationsReportsAddIndexRoute
  '/accl/policies-reports/add': typeof LayoutAcclPoliciesReportsAddIndexRoute
  '/research-reports/commodity-currency-reports/add': typeof LayoutResearchReportsCommodityCurrencyReportsAddIndexRoute
  '/research-reports/daily-insights-reports/add': typeof LayoutResearchReportsDailyInsightsReportsAddIndexRoute
  '/research-reports/fundamental-reports/add': typeof LayoutResearchReportsFundamentalReportsAddIndexRoute
  '/research-reports/monthly-insights-reports/add': typeof LayoutResearchReportsMonthlyInsightsReportsAddIndexRoute
  '/research-reports/mutual-fund-reports/add': typeof LayoutResearchReportsMutualFundReportsAddIndexRoute
  '/research-reports/special-reports/add': typeof LayoutResearchReportsSpecialReportsAddIndexRoute
  '/research-reports/weekly-insights-reports/add': typeof LayoutResearchReportsWeeklyInsightsReportsAddIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/add-client': typeof LayoutAddClientRoute
  '/test': typeof LayoutTestRoute
  '/downloads': typeof LayoutDownloadsIndexRoute
  '/fund-transfer': typeof LayoutFundTransferIndexRoute
  '/margin-updates': typeof LayoutMarginUpdatesIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/downloads/$reportId/update': typeof LayoutDownloadsReportIdUpdateRoute
  '/margin-updates/$reportId/update': typeof LayoutMarginUpdatesReportIdUpdateRoute
  '/accl/annual-reports': typeof LayoutAcclAnnualReportsIndexRoute
  '/accl/familiarization-programme-reports': typeof LayoutAcclFamiliarizationProgrammeReportsIndexRoute
  '/accl/investor-relations-reports': typeof LayoutAcclInvestorRelationsReportsIndexRoute
  '/accl/policies-reports': typeof LayoutAcclPoliciesReportsIndexRoute
  '/downloads/add': typeof LayoutDownloadsAddIndexRoute
  '/fund-transfer/add-client': typeof LayoutFundTransferAddClientIndexRoute
  '/margin-updates/add': typeof LayoutMarginUpdatesAddIndexRoute
  '/research-reports/commodity-currency-reports': typeof LayoutResearchReportsCommodityCurrencyReportsIndexRoute
  '/research-reports/daily-insights-reports': typeof LayoutResearchReportsDailyInsightsReportsIndexRoute
  '/research-reports/fundamental-reports': typeof LayoutResearchReportsFundamentalReportsIndexRoute
  '/research-reports/monthly-insights-reports': typeof LayoutResearchReportsMonthlyInsightsReportsIndexRoute
  '/research-reports/mutual-fund-reports': typeof LayoutResearchReportsMutualFundReportsIndexRoute
  '/research-reports/special-reports': typeof LayoutResearchReportsSpecialReportsIndexRoute
  '/research-reports/weekly-insights-reports': typeof LayoutResearchReportsWeeklyInsightsReportsIndexRoute
  '/users/add': typeof LayoutUsersAddIndexRoute
  '/accl/annual-reports/$reportId/update': typeof LayoutAcclAnnualReportsReportIdUpdateRoute
  '/accl/familiarization-programme-reports/$reportId/update': typeof LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateRoute
  '/accl/investor-relations-reports/$reportId/update': typeof LayoutAcclInvestorRelationsReportsReportIdUpdateRoute
  '/accl/policies-reports/$reportId/update': typeof LayoutAcclPoliciesReportsReportIdUpdateRoute
  '/research-reports/commodity-currency-reports/$reportId/update': typeof LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateRoute
  '/research-reports/daily-insights-reports/$reportId/update': typeof LayoutResearchReportsDailyInsightsReportsReportIdUpdateRoute
  '/research-reports/fundamental-reports/$reportId/update': typeof LayoutResearchReportsFundamentalReportsReportIdUpdateRoute
  '/research-reports/monthly-insights-reports/$reportId/update': typeof LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateRoute
  '/research-reports/mutual-fund-reports/$reportId/update': typeof LayoutResearchReportsMutualFundReportsReportIdUpdateRoute
  '/research-reports/special-reports/$reportId/update': typeof LayoutResearchReportsSpecialReportsReportIdUpdateRoute
  '/research-reports/weekly-insights-reports/$reportId/update': typeof LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateRoute
  '/accl/annual-reports/add': typeof LayoutAcclAnnualReportsAddIndexRoute
  '/accl/familiarization-programme-reports/add': typeof LayoutAcclFamiliarizationProgrammeReportsAddIndexRoute
  '/accl/investor-relations-reports/add': typeof LayoutAcclInvestorRelationsReportsAddIndexRoute
  '/accl/policies-reports/add': typeof LayoutAcclPoliciesReportsAddIndexRoute
  '/research-reports/commodity-currency-reports/add': typeof LayoutResearchReportsCommodityCurrencyReportsAddIndexRoute
  '/research-reports/daily-insights-reports/add': typeof LayoutResearchReportsDailyInsightsReportsAddIndexRoute
  '/research-reports/fundamental-reports/add': typeof LayoutResearchReportsFundamentalReportsAddIndexRoute
  '/research-reports/monthly-insights-reports/add': typeof LayoutResearchReportsMonthlyInsightsReportsAddIndexRoute
  '/research-reports/mutual-fund-reports/add': typeof LayoutResearchReportsMutualFundReportsAddIndexRoute
  '/research-reports/special-reports/add': typeof LayoutResearchReportsSpecialReportsAddIndexRoute
  '/research-reports/weekly-insights-reports/add': typeof LayoutResearchReportsWeeklyInsightsReportsAddIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/add-client': typeof LayoutAddClientRoute
  '/_layout/test': typeof LayoutTestRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/downloads/': typeof LayoutDownloadsIndexRoute
  '/_layout/fund-transfer/': typeof LayoutFundTransferIndexRoute
  '/_layout/margin-updates/': typeof LayoutMarginUpdatesIndexRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
  '/_layout/downloads/$reportId/update': typeof LayoutDownloadsReportIdUpdateRoute
  '/_layout/margin-updates/$reportId/update': typeof LayoutMarginUpdatesReportIdUpdateRoute
  '/_layout/accl/annual-reports/': typeof LayoutAcclAnnualReportsIndexRoute
  '/_layout/accl/familiarization-programme-reports/': typeof LayoutAcclFamiliarizationProgrammeReportsIndexRoute
  '/_layout/accl/investor-relations-reports/': typeof LayoutAcclInvestorRelationsReportsIndexRoute
  '/_layout/accl/policies-reports/': typeof LayoutAcclPoliciesReportsIndexRoute
  '/_layout/downloads/add/': typeof LayoutDownloadsAddIndexRoute
  '/_layout/fund-transfer/add-client/': typeof LayoutFundTransferAddClientIndexRoute
  '/_layout/margin-updates/add/': typeof LayoutMarginUpdatesAddIndexRoute
  '/_layout/research-reports/commodity-currency-reports/': typeof LayoutResearchReportsCommodityCurrencyReportsIndexRoute
  '/_layout/research-reports/daily-insights-reports/': typeof LayoutResearchReportsDailyInsightsReportsIndexRoute
  '/_layout/research-reports/fundamental-reports/': typeof LayoutResearchReportsFundamentalReportsIndexRoute
  '/_layout/research-reports/monthly-insights-reports/': typeof LayoutResearchReportsMonthlyInsightsReportsIndexRoute
  '/_layout/research-reports/mutual-fund-reports/': typeof LayoutResearchReportsMutualFundReportsIndexRoute
  '/_layout/research-reports/special-reports/': typeof LayoutResearchReportsSpecialReportsIndexRoute
  '/_layout/research-reports/weekly-insights-reports/': typeof LayoutResearchReportsWeeklyInsightsReportsIndexRoute
  '/_layout/users/add/': typeof LayoutUsersAddIndexRoute
  '/_layout/accl/annual-reports/$reportId/update': typeof LayoutAcclAnnualReportsReportIdUpdateRoute
  '/_layout/accl/familiarization-programme-reports/$reportId/update': typeof LayoutAcclFamiliarizationProgrammeReportsReportIdUpdateRoute
  '/_layout/accl/investor-relations-reports/$reportId/update': typeof LayoutAcclInvestorRelationsReportsReportIdUpdateRoute
  '/_layout/accl/policies-reports/$reportId/update': typeof LayoutAcclPoliciesReportsReportIdUpdateRoute
  '/_layout/research-reports/commodity-currency-reports/$reportId/update': typeof LayoutResearchReportsCommodityCurrencyReportsReportIdUpdateRoute
  '/_layout/research-reports/daily-insights-reports/$reportId/update': typeof LayoutResearchReportsDailyInsightsReportsReportIdUpdateRoute
  '/_layout/research-reports/fundamental-reports/$reportId/update': typeof LayoutResearchReportsFundamentalReportsReportIdUpdateRoute
  '/_layout/research-reports/monthly-insights-reports/$reportId/update': typeof LayoutResearchReportsMonthlyInsightsReportsReportIdUpdateRoute
  '/_layout/research-reports/mutual-fund-reports/$reportId/update': typeof LayoutResearchReportsMutualFundReportsReportIdUpdateRoute
  '/_layout/research-reports/special-reports/$reportId/update': typeof LayoutResearchReportsSpecialReportsReportIdUpdateRoute
  '/_layout/research-reports/weekly-insights-reports/$reportId/update': typeof LayoutResearchReportsWeeklyInsightsReportsReportIdUpdateRoute
  '/_layout/accl/annual-reports/add/': typeof LayoutAcclAnnualReportsAddIndexRoute
  '/_layout/accl/familiarization-programme-reports/add/': typeof LayoutAcclFamiliarizationProgrammeReportsAddIndexRoute
  '/_layout/accl/investor-relations-reports/add/': typeof LayoutAcclInvestorRelationsReportsAddIndexRoute
  '/_layout/accl/policies-reports/add/': typeof LayoutAcclPoliciesReportsAddIndexRoute
  '/_layout/research-reports/commodity-currency-reports/add/': typeof LayoutResearchReportsCommodityCurrencyReportsAddIndexRoute
  '/_layout/research-reports/daily-insights-reports/add/': typeof LayoutResearchReportsDailyInsightsReportsAddIndexRoute
  '/_layout/research-reports/fundamental-reports/add/': typeof LayoutResearchReportsFundamentalReportsAddIndexRoute
  '/_layout/research-reports/monthly-insights-reports/add/': typeof LayoutResearchReportsMonthlyInsightsReportsAddIndexRoute
  '/_layout/research-reports/mutual-fund-reports/add/': typeof LayoutResearchReportsMutualFundReportsAddIndexRoute
  '/_layout/research-reports/special-reports/add/': typeof LayoutResearchReportsSpecialReportsAddIndexRoute
  '/_layout/research-reports/weekly-insights-reports/add/': typeof LayoutResearchReportsWeeklyInsightsReportsAddIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/add-client'
    | '/test'
    | '/downloads'
    | '/fund-transfer'
    | '/margin-updates'
    | '/users'
    | '/downloads/$reportId/update'
    | '/margin-updates/$reportId/update'
    | '/accl/annual-reports'
    | '/accl/familiarization-programme-reports'
    | '/accl/investor-relations-reports'
    | '/accl/policies-reports'
    | '/downloads/add'
    | '/fund-transfer/add-client'
    | '/margin-updates/add'
    | '/research-reports/commodity-currency-reports'
    | '/research-reports/daily-insights-reports'
    | '/research-reports/fundamental-reports'
    | '/research-reports/monthly-insights-reports'
    | '/research-reports/mutual-fund-reports'
    | '/research-reports/special-reports'
    | '/research-reports/weekly-insights-reports'
    | '/users/add'
    | '/accl/annual-reports/$reportId/update'
    | '/accl/familiarization-programme-reports/$reportId/update'
    | '/accl/investor-relations-reports/$reportId/update'
    | '/accl/policies-reports/$reportId/update'
    | '/research-reports/commodity-currency-reports/$reportId/update'
    | '/research-reports/daily-insights-reports/$reportId/update'
    | '/research-reports/fundamental-reports/$reportId/update'
    | '/research-reports/monthly-insights-reports/$reportId/update'
    | '/research-reports/mutual-fund-reports/$reportId/update'
    | '/research-reports/special-reports/$reportId/update'
    | '/research-reports/weekly-insights-reports/$reportId/update'
    | '/accl/annual-reports/add'
    | '/accl/familiarization-programme-reports/add'
    | '/accl/investor-relations-reports/add'
    | '/accl/policies-reports/add'
    | '/research-reports/commodity-currency-reports/add'
    | '/research-reports/daily-insights-reports/add'
    | '/research-reports/fundamental-reports/add'
    | '/research-reports/monthly-insights-reports/add'
    | '/research-reports/mutual-fund-reports/add'
    | '/research-reports/special-reports/add'
    | '/research-reports/weekly-insights-reports/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-client'
    | '/test'
    | '/downloads'
    | '/fund-transfer'
    | '/margin-updates'
    | '/users'
    | '/downloads/$reportId/update'
    | '/margin-updates/$reportId/update'
    | '/accl/annual-reports'
    | '/accl/familiarization-programme-reports'
    | '/accl/investor-relations-reports'
    | '/accl/policies-reports'
    | '/downloads/add'
    | '/fund-transfer/add-client'
    | '/margin-updates/add'
    | '/research-reports/commodity-currency-reports'
    | '/research-reports/daily-insights-reports'
    | '/research-reports/fundamental-reports'
    | '/research-reports/monthly-insights-reports'
    | '/research-reports/mutual-fund-reports'
    | '/research-reports/special-reports'
    | '/research-reports/weekly-insights-reports'
    | '/users/add'
    | '/accl/annual-reports/$reportId/update'
    | '/accl/familiarization-programme-reports/$reportId/update'
    | '/accl/investor-relations-reports/$reportId/update'
    | '/accl/policies-reports/$reportId/update'
    | '/research-reports/commodity-currency-reports/$reportId/update'
    | '/research-reports/daily-insights-reports/$reportId/update'
    | '/research-reports/fundamental-reports/$reportId/update'
    | '/research-reports/monthly-insights-reports/$reportId/update'
    | '/research-reports/mutual-fund-reports/$reportId/update'
    | '/research-reports/special-reports/$reportId/update'
    | '/research-reports/weekly-insights-reports/$reportId/update'
    | '/accl/annual-reports/add'
    | '/accl/familiarization-programme-reports/add'
    | '/accl/investor-relations-reports/add'
    | '/accl/policies-reports/add'
    | '/research-reports/commodity-currency-reports/add'
    | '/research-reports/daily-insights-reports/add'
    | '/research-reports/fundamental-reports/add'
    | '/research-reports/monthly-insights-reports/add'
    | '/research-reports/mutual-fund-reports/add'
    | '/research-reports/special-reports/add'
    | '/research-reports/weekly-insights-reports/add'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/add-client'
    | '/_layout/test'
    | '/_layout/'
    | '/_layout/downloads/'
    | '/_layout/fund-transfer/'
    | '/_layout/margin-updates/'
    | '/_layout/users/'
    | '/_layout/downloads/$reportId/update'
    | '/_layout/margin-updates/$reportId/update'
    | '/_layout/accl/annual-reports/'
    | '/_layout/accl/familiarization-programme-reports/'
    | '/_layout/accl/investor-relations-reports/'
    | '/_layout/accl/policies-reports/'
    | '/_layout/downloads/add/'
    | '/_layout/fund-transfer/add-client/'
    | '/_layout/margin-updates/add/'
    | '/_layout/research-reports/commodity-currency-reports/'
    | '/_layout/research-reports/daily-insights-reports/'
    | '/_layout/research-reports/fundamental-reports/'
    | '/_layout/research-reports/monthly-insights-reports/'
    | '/_layout/research-reports/mutual-fund-reports/'
    | '/_layout/research-reports/special-reports/'
    | '/_layout/research-reports/weekly-insights-reports/'
    | '/_layout/users/add/'
    | '/_layout/accl/annual-reports/$reportId/update'
    | '/_layout/accl/familiarization-programme-reports/$reportId/update'
    | '/_layout/accl/investor-relations-reports/$reportId/update'
    | '/_layout/accl/policies-reports/$reportId/update'
    | '/_layout/research-reports/commodity-currency-reports/$reportId/update'
    | '/_layout/research-reports/daily-insights-reports/$reportId/update'
    | '/_layout/research-reports/fundamental-reports/$reportId/update'
    | '/_layout/research-reports/monthly-insights-reports/$reportId/update'
    | '/_layout/research-reports/mutual-fund-reports/$reportId/update'
    | '/_layout/research-reports/special-reports/$reportId/update'
    | '/_layout/research-reports/weekly-insights-reports/$reportId/update'
    | '/_layout/accl/annual-reports/add/'
    | '/_layout/accl/familiarization-programme-reports/add/'
    | '/_layout/accl/investor-relations-reports/add/'
    | '/_layout/accl/policies-reports/add/'
    | '/_layout/research-reports/commodity-currency-reports/add/'
    | '/_layout/research-reports/daily-insights-reports/add/'
    | '/_layout/research-reports/fundamental-reports/add/'
    | '/_layout/research-reports/monthly-insights-reports/add/'
    | '/_layout/research-reports/mutual-fund-reports/add/'
    | '/_layout/research-reports/special-reports/add/'
    | '/_layout/research-reports/weekly-insights-reports/add/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/add-client",
        "/_layout/test",
        "/_layout/",
        "/_layout/downloads/",
        "/_layout/fund-transfer/",
        "/_layout/margin-updates/",
        "/_layout/users/",
        "/_layout/downloads/$reportId/update",
        "/_layout/margin-updates/$reportId/update",
        "/_layout/accl/annual-reports/",
        "/_layout/accl/familiarization-programme-reports/",
        "/_layout/accl/investor-relations-reports/",
        "/_layout/accl/policies-reports/",
        "/_layout/downloads/add/",
        "/_layout/fund-transfer/add-client/",
        "/_layout/margin-updates/add/",
        "/_layout/research-reports/commodity-currency-reports/",
        "/_layout/research-reports/daily-insights-reports/",
        "/_layout/research-reports/fundamental-reports/",
        "/_layout/research-reports/monthly-insights-reports/",
        "/_layout/research-reports/mutual-fund-reports/",
        "/_layout/research-reports/special-reports/",
        "/_layout/research-reports/weekly-insights-reports/",
        "/_layout/users/add/",
        "/_layout/accl/annual-reports/$reportId/update",
        "/_layout/accl/familiarization-programme-reports/$reportId/update",
        "/_layout/accl/investor-relations-reports/$reportId/update",
        "/_layout/accl/policies-reports/$reportId/update",
        "/_layout/research-reports/commodity-currency-reports/$reportId/update",
        "/_layout/research-reports/daily-insights-reports/$reportId/update",
        "/_layout/research-reports/fundamental-reports/$reportId/update",
        "/_layout/research-reports/monthly-insights-reports/$reportId/update",
        "/_layout/research-reports/mutual-fund-reports/$reportId/update",
        "/_layout/research-reports/special-reports/$reportId/update",
        "/_layout/research-reports/weekly-insights-reports/$reportId/update",
        "/_layout/accl/annual-reports/add/",
        "/_layout/accl/familiarization-programme-reports/add/",
        "/_layout/accl/investor-relations-reports/add/",
        "/_layout/accl/policies-reports/add/",
        "/_layout/research-reports/commodity-currency-reports/add/",
        "/_layout/research-reports/daily-insights-reports/add/",
        "/_layout/research-reports/fundamental-reports/add/",
        "/_layout/research-reports/monthly-insights-reports/add/",
        "/_layout/research-reports/mutual-fund-reports/add/",
        "/_layout/research-reports/special-reports/add/",
        "/_layout/research-reports/weekly-insights-reports/add/"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/add-client": {
      "filePath": "_layout/add-client.tsx",
      "parent": "/_layout"
    },
    "/_layout/test": {
      "filePath": "_layout/test.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/downloads/": {
      "filePath": "_layout/downloads/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/fund-transfer/": {
      "filePath": "_layout/fund-transfer/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/margin-updates/": {
      "filePath": "_layout/margin-updates/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/users/": {
      "filePath": "_layout/users/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/downloads/$reportId/update": {
      "filePath": "_layout/downloads/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/margin-updates/$reportId/update": {
      "filePath": "_layout/margin-updates/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/annual-reports/": {
      "filePath": "_layout/accl/annual-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/familiarization-programme-reports/": {
      "filePath": "_layout/accl/familiarization-programme-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/investor-relations-reports/": {
      "filePath": "_layout/accl/investor-relations-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/policies-reports/": {
      "filePath": "_layout/accl/policies-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/downloads/add/": {
      "filePath": "_layout/downloads/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/fund-transfer/add-client/": {
      "filePath": "_layout/fund-transfer/add-client/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/margin-updates/add/": {
      "filePath": "_layout/margin-updates/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/commodity-currency-reports/": {
      "filePath": "_layout/research-reports/commodity-currency-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/daily-insights-reports/": {
      "filePath": "_layout/research-reports/daily-insights-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/fundamental-reports/": {
      "filePath": "_layout/research-reports/fundamental-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/monthly-insights-reports/": {
      "filePath": "_layout/research-reports/monthly-insights-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/mutual-fund-reports/": {
      "filePath": "_layout/research-reports/mutual-fund-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/special-reports/": {
      "filePath": "_layout/research-reports/special-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/weekly-insights-reports/": {
      "filePath": "_layout/research-reports/weekly-insights-reports/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/users/add/": {
      "filePath": "_layout/users/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/annual-reports/$reportId/update": {
      "filePath": "_layout/accl/annual-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/familiarization-programme-reports/$reportId/update": {
      "filePath": "_layout/accl/familiarization-programme-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/investor-relations-reports/$reportId/update": {
      "filePath": "_layout/accl/investor-relations-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/policies-reports/$reportId/update": {
      "filePath": "_layout/accl/policies-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/commodity-currency-reports/$reportId/update": {
      "filePath": "_layout/research-reports/commodity-currency-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/daily-insights-reports/$reportId/update": {
      "filePath": "_layout/research-reports/daily-insights-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/fundamental-reports/$reportId/update": {
      "filePath": "_layout/research-reports/fundamental-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/monthly-insights-reports/$reportId/update": {
      "filePath": "_layout/research-reports/monthly-insights-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/mutual-fund-reports/$reportId/update": {
      "filePath": "_layout/research-reports/mutual-fund-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/special-reports/$reportId/update": {
      "filePath": "_layout/research-reports/special-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/weekly-insights-reports/$reportId/update": {
      "filePath": "_layout/research-reports/weekly-insights-reports/$reportId/update.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/annual-reports/add/": {
      "filePath": "_layout/accl/annual-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/familiarization-programme-reports/add/": {
      "filePath": "_layout/accl/familiarization-programme-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/investor-relations-reports/add/": {
      "filePath": "_layout/accl/investor-relations-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/accl/policies-reports/add/": {
      "filePath": "_layout/accl/policies-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/commodity-currency-reports/add/": {
      "filePath": "_layout/research-reports/commodity-currency-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/daily-insights-reports/add/": {
      "filePath": "_layout/research-reports/daily-insights-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/fundamental-reports/add/": {
      "filePath": "_layout/research-reports/fundamental-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/monthly-insights-reports/add/": {
      "filePath": "_layout/research-reports/monthly-insights-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/mutual-fund-reports/add/": {
      "filePath": "_layout/research-reports/mutual-fund-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/special-reports/add/": {
      "filePath": "_layout/research-reports/special-reports/add/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/research-reports/weekly-insights-reports/add/": {
      "filePath": "_layout/research-reports/weekly-insights-reports/add/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
